// Platform-level mock data: multiple stores, users, platform metrics
import type { PlatformStore, PlatformUser } from "@/lib/types/platform";

function relativeDate(daysOffset: number): string {
  const d = new Date();
  d.setDate(d.getDate() + daysOffset);
  return d.toISOString().split("T")[0];
}

export const platformStores: PlatformStore[] = [
  {
    id: "s1",
    name: "홍대 트러플 파스타",
    category: "이탈리안",
    address: "서울 마포구 와우산로 21",
    ownerName: "김민수",
    ownerEmail: "minsu@example.com",
    phone: "02-1234-5678",
    plan: "pro",
    status: "active",
    diagnosticScore: 72,
    reviewCount: 328,
    rating: 4.2,
    monthlyOrders: 245,
    monthlyBookings: 89,
    monthlyRevenue: 12500000,
    signupDate: relativeDate(-45),
    lastActiveDate: relativeDate(0),
  },
  {
    id: "s2",
    name: "강남 스시오마카세",
    category: "일식",
    address: "서울 강남구 역삼로 15",
    ownerName: "박지영",
    ownerEmail: "jiyoung@example.com",
    phone: "02-9876-5432",
    plan: "enterprise",
    status: "active",
    diagnosticScore: 88,
    reviewCount: 512,
    rating: 4.7,
    monthlyOrders: 120,
    monthlyBookings: 210,
    monthlyRevenue: 28000000,
    signupDate: relativeDate(-90),
    lastActiveDate: relativeDate(0),
  },
  {
    id: "s3",
    name: "이태원 타코 하우스",
    category: "멕시칸",
    address: "서울 용산구 이태원로 42",
    ownerName: "이준혁",
    ownerEmail: "junhyuk@example.com",
    phone: "02-5555-1234",
    plan: "basic",
    status: "active",
    diagnosticScore: 55,
    reviewCount: 156,
    rating: 3.9,
    monthlyOrders: 178,
    monthlyBookings: 32,
    monthlyRevenue: 6800000,
    signupDate: relativeDate(-30),
    lastActiveDate: relativeDate(-1),
  },
  {
    id: "s4",
    name: "성수 브런치 카페",
    category: "카페/브런치",
    address: "서울 성동구 연무장길 8",
    ownerName: "최서연",
    ownerEmail: "seoyeon@example.com",
    phone: "02-3333-4444",
    plan: "pro",
    status: "active",
    diagnosticScore: 81,
    reviewCount: 423,
    rating: 4.5,
    monthlyOrders: 310,
    monthlyBookings: 65,
    monthlyRevenue: 9200000,
    signupDate: relativeDate(-60),
    lastActiveDate: relativeDate(0),
  },
  {
    id: "s5",
    name: "망원 돈카츠",
    category: "일식/돈카츠",
    address: "서울 마포구 망원로 33",
    ownerName: "정태호",
    ownerEmail: "taeho@example.com",
    phone: "02-7777-8888",
    plan: "free",
    status: "trial",
    diagnosticScore: 42,
    reviewCount: 67,
    rating: 4.0,
    monthlyOrders: 95,
    monthlyBookings: 15,
    monthlyRevenue: 3200000,
    signupDate: relativeDate(-7),
    lastActiveDate: relativeDate(-1),
  },
  {
    id: "s6",
    name: "연남 베트남 쌀국수",
    category: "베트남",
    address: "서울 마포구 연남로 11",
    ownerName: "한소희",
    ownerEmail: "sohee@example.com",
    phone: "02-2222-3333",
    plan: "basic",
    status: "active",
    diagnosticScore: 63,
    reviewCount: 198,
    rating: 4.1,
    monthlyOrders: 220,
    monthlyBookings: 28,
    monthlyRevenue: 5400000,
    signupDate: relativeDate(-40),
    lastActiveDate: relativeDate(-2),
  },
  {
    id: "s7",
    name: "합정 수제버거",
    category: "버거",
    address: "서울 마포구 합정로 7",
    ownerName: "윤재민",
    ownerEmail: "jaemin@example.com",
    phone: "02-4444-5555",
    plan: "pro",
    status: "active",
    diagnosticScore: 76,
    reviewCount: 287,
    rating: 4.3,
    monthlyOrders: 350,
    monthlyBookings: 0,
    monthlyRevenue: 8900000,
    signupDate: relativeDate(-55),
    lastActiveDate: relativeDate(0),
  },
  {
    id: "s8",
    name: "종로 한정식",
    category: "한식",
    address: "서울 종로구 율곡로 28",
    ownerName: "김영희",
    ownerEmail: "younghee@example.com",
    phone: "02-6666-7777",
    plan: "enterprise",
    status: "active",
    diagnosticScore: 91,
    reviewCount: 645,
    rating: 4.8,
    monthlyOrders: 85,
    monthlyBookings: 320,
    monthlyRevenue: 42000000,
    signupDate: relativeDate(-120),
    lastActiveDate: relativeDate(0),
  },
  {
    id: "s9",
    name: "건대 떡볶이 연구소",
    category: "분식",
    address: "서울 광진구 능동로 55",
    ownerName: "오민지",
    ownerEmail: "minji@example.com",
    phone: "02-1111-2222",
    plan: "free",
    status: "churned",
    diagnosticScore: 35,
    reviewCount: 89,
    rating: 3.6,
    monthlyOrders: 0,
    monthlyBookings: 0,
    monthlyRevenue: 0,
    signupDate: relativeDate(-80),
    lastActiveDate: relativeDate(-30),
  },
  {
    id: "s10",
    name: "신촌 치킨 팩토리",
    category: "치킨",
    address: "서울 서대문구 연세로 19",
    ownerName: "장우성",
    ownerEmail: "woosung@example.com",
    phone: "02-8888-9999",
    plan: "basic",
    status: "active",
    diagnosticScore: 58,
    reviewCount: 234,
    rating: 4.0,
    monthlyOrders: 420,
    monthlyBookings: 0,
    monthlyRevenue: 7600000,
    signupDate: relativeDate(-25),
    lastActiveDate: relativeDate(0),
  },
  {
    id: "s11",
    name: "압구정 디저트바",
    category: "디저트",
    address: "서울 강남구 압구정로 50",
    ownerName: "나은비",
    ownerEmail: "eunbi@example.com",
    phone: "02-5050-6060",
    plan: "pro",
    status: "trial",
    diagnosticScore: 69,
    reviewCount: 175,
    rating: 4.4,
    monthlyOrders: 130,
    monthlyBookings: 45,
    monthlyRevenue: 5100000,
    signupDate: relativeDate(-5),
    lastActiveDate: relativeDate(0),
  },
  {
    id: "s12",
    name: "을지로 노포 냉면",
    category: "한식",
    address: "서울 중구 을지로 38",
    ownerName: "백종원",
    ownerEmail: "jongwon@example.com",
    phone: "02-3030-4040",
    plan: "free",
    status: "suspended",
    diagnosticScore: 28,
    reviewCount: 412,
    rating: 4.6,
    monthlyOrders: 0,
    monthlyBookings: 0,
    monthlyRevenue: 0,
    signupDate: relativeDate(-100),
    lastActiveDate: relativeDate(-45),
  },
];

export const platformUsers: PlatformUser[] = platformStores.map((store) => ({
  id: `u-${store.id}`,
  name: store.ownerName,
  email: store.ownerEmail,
  phone: store.phone,
  storeName: store.name,
  storeId: store.id,
  role: "owner" as const,
  plan: store.plan,
  status: store.status === "active" || store.status === "trial" ? "active" as const : "inactive" as const,
  signupDate: store.signupDate,
  lastLoginDate: store.lastActiveDate,
}));

// Add some extra staff/manager users
platformUsers.push(
  {
    id: "u-extra-1",
    name: "김서현",
    email: "seohyun@example.com",
    phone: "010-1234-5678",
    storeName: "강남 스시오마카세",
    storeId: "s2",
    role: "manager",
    plan: "enterprise",
    status: "active",
    signupDate: relativeDate(-60),
    lastLoginDate: relativeDate(-1),
  },
  {
    id: "u-extra-2",
    name: "이하준",
    email: "hajun@example.com",
    phone: "010-9876-5432",
    storeName: "종로 한정식",
    storeId: "s8",
    role: "manager",
    plan: "enterprise",
    status: "active",
    signupDate: relativeDate(-90),
    lastLoginDate: relativeDate(0),
  },
  {
    id: "u-extra-3",
    name: "조예린",
    email: "yerin@example.com",
    phone: "010-5555-6666",
    storeName: "홍대 트러플 파스타",
    storeId: "s1",
    role: "staff",
    plan: "pro",
    status: "active",
    signupDate: relativeDate(-20),
    lastLoginDate: relativeDate(-3),
  },
);

// getPlatformMetrics removed — use computeMetrics() from platform-store.ts instead
